global:
    hide_tables: ['']
    default_server: "proxysql"
    read_only:  false

servers:
    proxysql:
      dsn:
        - { "host": "127.0.0.1", "user": "admin", "passwd": "admin", "port": "6032", "db": "main"}


#   proxysql_local_docker_no_host:
#     dsn:
#       - { "host": "172.17.0.1", "user": "radmin", "passwd": "radmin", "port": "6032", "db": "main"}
#   proxysql_remote_read_only:
#     dsn:
#       - { "host": "10.77.10.23, "user": "radmin", "passwd": "radmin", "port": "6032", "db": "main"}
#     read_only: true
## it's possible to hide tables that won't be used  - like aurora, galera related ones
#   proxysql_remote_with_hidden_tables:
#     dsn:
#       - { "host": "10.77.10.24", "user": "arthur", "passwd": "zaphod", "port": "6032", "db": "main"}
#     hide_tables: ['mysql_aws_aurora_hostgroups', 'mysql_server_aws_aurora_failovers', 'mysql_server_aws_aurora_check_status', 'mysql_server_group_replication_log', 'mysql_server_aws_aurora_log' , 'mysql_server_aws_aurora_log', 'runtime_mysql_aws_aurora_hostgroups', 'runtime_mysql_server_aws_aurora_failovers', 'runtime_mysql_server_aws_aurora_check_status', 'runtime_mysql_server_group_replication_log', 'runtime_mysql_server_aws_aurora_log', 'runtime_mysql_server_aws_aurora_log']

flask:
    SECRET_KEY: "12345678901234567890"
    SEND_FILE_MAX_AGE_DEFAULT: 0 
    TEMPLATES_AUTO_RELOAD: "True"


