addr:
{{range .Vars.dbs}}
  tcp://{{.}}:3306:
    reachable: true
    timeout: 500
{{end}}
{{range .Vars.proxysqls}}
  tcp://{{.}}:6032:
    reachable: true
    timeout: 500
{{end}}
{{range .Vars.proxysqls}}
  tcp://{{.}}:6033:
    reachable: true
    timeout: 500
{{end}}

  tcp://proxyweb:5000:
    reachable: true
    timeout: 500

  tcp://orchestrator:3000:
    reachable: true
    timeout: 500

#command:
#  version:
#    # required attributes
#    exit-status: 0
#    # defaults to hash key
#    exec: "mysql -NB -h 0.0.0.0 -P6032 -e 'select @@version'"
#    # optional attributes
#    stdout:
#    - "2.1.0-544-g17a4b4a7"
#    stderr: []
#    timeout: 10000 # in milliseconds
#    skip: false
